### PR TITLE
implement --tld

### PR DESCRIPTION
**Pull request by disenchant**
As we quite often need to stay on the same TLD in our phishing engagements I've implemented a `--tld` switch that allows a user to choose a specific TLD.

```
$ ruby ./catphish.rb -d example.com -a --tld shop

 ██████╗ █████╗ ████████╗██████╗ ██╗  ██╗██╗███████╗██╗  ██╗
██╔════╝██╔══██╗╚══██╔══╝██╔══██╗██║  ██║██║██╔════╝██║  ██║
██║     ███████║   ██║   ██████╔╝███████║██║███████╗███████║
██║     ██╔══██║   ██║   ██╔═══╝ ██╔══██║██║╚════██║██╔══██║
╚██████╗██║  ██║   ██║   ██║     ██║  ██║██║███████║██║  ██║
 ╚═════╝╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═╝╚══════╝╚═╝  ╚═╝
                                                    [v]0.0.6
                                               Author: Mr. V
                                           Web: ring0lab.com
Type                           Domain                         Status

prependOrAppend                example-www.shop               Available
doubleExtensions               example-com.shop               Available
homoglyphs                     exampie.shop                   Available
mirrorization                  example.shop                   Available
mirrorization                  exaaple.shop                   Available
homoglyphs                     exarmple.shop                  Available
mirrorization                  examppe.shop                   Available
mirrorization                  examplle.shop                  Available
mirrorization                  examplee.shop                  Available
prependOrAppend                www-example.shop               Available
prependOrAppend                http-example.shop              Available
prependOrAppend                example-https.shop             Available
standard                       example.shop                   Available
SingularOrPluralise            examples.shop                  Available
homoglyphs                     examqle.shop                   Available
mirrorization                  exxmple.shop                   Available
mirrorization                  exammle.shop                   Available
```

PS: I've also included some formatting 😃

### CODE REVIEW

**Comment by picatz** [comment]
Nice!

Now I just need to implement this into the thing I'm also implementing. 🤣

**Comment by disenchant** [comment]
@picatz anything I could be of help?

**Comment by picatz** [comment]
@disenchant Looks like I go it to work without much of a fuss. 👍

**Comment by ring0lab** [comment]
This feature is included in the House Cleaning Service merge.

**Pull request closed without merging**
